### ISSUE TITLE
Create a `useLoop` hook to create an animated gradient effect.

### ISSUE THREAD

**Issue by Angel-Ponce** [carlos-dubon/react-animated-gradient#2]
In your documentation you expose the following `useEffect` to create an infinite gradient loop effect:

```tsx
 useEffect(() => {
    const interval = setInterval(() => {
      if (currentGradientIndex === props.colors.length - 1) {
        setCurrentGradientIndex(0);
      } else {
        setCurrentGradientIndex((prev) => prev + 1);
      }
    }, 1000);

    return () => {
      clearInterval(interval);
    };
  }, [currentGradientIndex, props.colors]);
```

Do this functionality a custom hook exported by your package to quickly use an infinte loop without the needed of copy your snippet.

**Comment by carlos-dubon** [comment]
It doesn't have that hook ok on purpose. This is an unopinionated library. So this won't be implemented :)... 

Think of this library as a core package that can easily be extended by the community. Something like `Headless UI` by the Tailwind team or `shadcn/ui`. They could easily style their dropdown components, but that defeats the purpose of those libraries.

You can create your own `react-infinite-loop-gradient` npm package, and use this library behind the scenes.

For further reading on `unopinionated architecture` I recommend reading the following SO:

https://stackoverflow.com/questions/802050/what-is-opinionated-software

**Comment by Angel-Ponce** [comment]
Uhm, I catch you!
